version: '3.8'

services:
  qradar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daangn-service-qradar
    restart: always
    ports:
      - "3010:3000"
    env_file:
      - .env.production
