version: '3.8'

services:
  helpdesk-x:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daangn-service-helpdesk-x
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
